export interface ModelConfig {
    id: string;
    type: 'text' | 'image' | 'audio' | 'video'; // Added 'video' type
    cost: number;
    quality: 'low' | 'medium' | 'high';
    avg_latency_ms?: number;
}
  
export interface ProviderConfig {
    name: string;
    apiKey: string;
    models: ModelConfig[];
    
    // --- Generic properties for the Custom Adapter ---
    baseUrl?: string;
    healthCheckEndpoint?: string;

    // Defines the name of the header for authentication. Defaults to 'Authorization'.
    // For one-api, you would set this to: 'one-api-token'
    authenticationHeader?: string;

    // Defines a prefix for the apiKey, e.g., 'Bearer '. Defaults to an empty string.
    authenticationScheme?: string;

    // A stringified JSON object defining the request body structure with placeholders.
    // Example for one-api: '[{ "role": "user", "content": "{{prompt}}" }]'
    requestBodyTemplate?: string;

    // A dot-notation path to extract the final text from the response JSON.
    // Example for one-api: 'result[0]'
    responseExtractor?: string;
}
  
export interface OrchestratorConfig {
    providers: ProviderConfig[];
    logger?: any; // Allow consumer to pass in a logger like pino or winston
}
  
export interface GenerateRequest {
    type: 'text' | 'image' | 'audio' | 'video';
    prompt: string;
    strategy?: 'cost' | 'latency' | 'quality';
    quality?: 'low' | 'medium' | 'high';
}


// Represents the immediate result from a `generate` call
export interface GenerateResult {
    status: 'completed' | 'pending' | 'failed';
    orchestratorJobId?: string; // A unique ID generated by our orchestrator
    provider: string;
    model: string;
    data?: string | Buffer; // Optional now, only present if status is 'completed'
    error?: string;
}

// Represents the result from polling a job's status
export interface JobStatusResult {
    status: 'pending' | 'completed' | 'failed';
    data?: string | Buffer; // The final data if the job is complete
    error?: string;
}
  
export interface IProviderAdapter {
    generate(request: GenerateRequest, modelId: string): Promise<GenerateResult>;
    // Optional method for providers that support async operations
    checkJobStatus?(providerJobId: string): Promise<JobStatusResult>;
}